-- 회원
 CREATE TABLE MEMBER (
	MEM_ID VARCHAR2(10) NOT NULL,
	MEM_NAME VARCHAR2(10) NOT NULL,
	MEM_PASS VARCHAR2(20) NOT NULL,
	MEM_ADDR VARCHAR2(100) NOT NULL,
	MEM_BIR DATE NOT NULL,
	MEM_RANK VARCHAR2(10) NOT NULL,
	MEM_MILE NUMBER(7) NOT NULL,
	MEM_BANK VARCHAR2(10) NOT NULL,
	MEM_ACC NUMBER(20) NOT NULL
);

-- 회원
ALTER TABLE MEMBER
	ADD CONSTRAINT PK_MEMBER -- 회원 기본키
	PRIMARY KEY (
	MEM_ID -- 회원아이디
	);

-- 관리자
CREATE TABLE ADMIN (
	ADM_ID VARCHAR2(10) NOT NULL,
	ADM_PASS VARCHAR2(20) NOT NULL,
	ADM_ACC NUMBER(20) NOT NULL,
	ADM_BANK VARCHAR2(10) NOT NULL
);

-- 관리자
ALTER TABLE ADMIN
	ADD CONSTRAINT PK_ADMIN -- 관리자 기본키
	PRIMARY KEY (
	ADM_ID -- 관리자아이디
	);

-- 사이즈별 상품
CREATE TABLE PROD_SIZE (
	SPROD_NO NUMBER(10) NOT NULL,
	SPROD_QTY NUMBER(5) NOT NULL,
	SPROD_SIZE VARCHAR2(5) NOT NULL,
	PROD_NO NUMBER(10) NULL
);

-- 사이즈별 상품
ALTER TABLE PROD_SIZE
	ADD CONSTRAINT PK_PROD_SIZE -- 사이즈별 상품 기본키
	PRIMARY KEY (
	SPROD_NO -- 사이즈별 상품번호
	);

-- 상품분류
CREATE TABLE LPROD (
	LPROD_NO VARCHAR2(10) NOT NULL,
	LPROD_NAME VARCHAR2(40) NOT NULL
);

-- 상품분류
ALTER TABLE LPROD
	ADD CONSTRAINT PK_LPROD -- 상품분류 기본키
	PRIMARY KEY (
	LPROD_NO -- 상품분류코드
	);

-- 리뷰
CREATE TABLE REVIEW (
	REV_NO NUMBER(10) NOT NULL,
	REV_TITLE VARCHAR2(100) NOT NULL,
	REV_CONTENT VARCHAR2(500) NOT NULL,
	REV_DATE DATE NOT NULL,
	REV_STAR NUMBER(10) NOT NULL,
	SPROD_NO NUMBER(10) NOT NULL,
	MEM_ID VARCHAR2(10) NOT NULL
);

-- 리뷰
ALTER TABLE REVIEW
	ADD CONSTRAINT PK_REVIEW -- 리뷰 기본키
	PRIMARY KEY (
	REV_NO -- 리뷰번호
	);

-- 주문
CREATE TABLE ORDERS (
	ORD_NO NUMBER(10) NOT NULL,
	MEM_ID VARCHAR2(10) NOT NULL,
	ORD_PRICE NUMBER(8) NOT NULL,
	ORD_DATE DATE NOT NULL
);

-- 주문
ALTER TABLE ORDERS
	ADD CONSTRAINT PK_ORDERS -- 주문 기본키
	PRIMARY KEY (
	ORD_NO -- 주문번호
	);

-- 결제수단
CREATE TABLE PAY_TYPE (
	PAY_TCODE VARCHAR2(10) NOT NULL,
	PAY_TNAME NUMBER(10) NOT NULL
);

-- 결제수단
ALTER TABLE PAY_TYPE
	ADD CONSTRAINT PK_PAY_TYPE -- 결제수단 기본키
	PRIMARY KEY (
	PAY_TCODE -- 결제수단코드
	);

-- 환불
CREATE TABLE REFUND (
	ORD_NO NUMBER(10) NOT NULL,
	REF_DATE DATE NOT NULL,
	REF_TNAME VARCHAR2(10) NOT NULL
);

-- 환불
ALTER TABLE REFUND
	ADD CONSTRAINT PK_REFUND -- 환불 기본키
	PRIMARY KEY (
	ORD_NO -- 환불번호
	);

-- 주문상세
CREATE TABLE DEORDER (
	ORD_NO NUMBER(10) NOT NULL,
	SPROD_NO NUMBER(10) NOT NULL,
	DEORDER_QTY NUMBER(5) NOT NULL
);

-- 주문상세
ALTER TABLE DEORDER
	ADD CONSTRAINT PK_DEORDER -- 주문상세 기본키
	PRIMARY KEY (
	ORD_NO,   -- 주문번호
	SPROD_NO  -- 사이즈별 상품번호
	);

-- 공지사항
CREATE TABLE NOTICE (
	NOTICE_NO NUMBER(10) NOT NULL,
	NOTICE_TITLE VARCHAR(50) NOT NULL,
	NOTICE_CONTENT VARCHAR(500) NOT NULL,
	NOTICE_DATE DATE NOT NULL,
	ADM_ID VARCHAR2(10) NOT NULL
);

-- 공지사항
ALTER TABLE NOTICE
	ADD CONSTRAINT PK_NOTICE -- 공지사항 기본키
	PRIMARY KEY (
	NOTICE_NO -- 공지글번호
	);

-- 상품질문게시판
CREATE TABLE QNA (
	PR_QNA_NO NUMBER(10) NOT NULL,
	PR_QNA_TITLE VARCHAR(50) NOT NULL,
	PR_QNA_CONTENT VARCHAR(500) NOT NULL,
	PR_QNA_DATE DATE NOT NULL,
	MEM_ID VARCHAR2(10) NOT NULL,
	SPROD_NO NUMBER(10) NOT NULL,
	PR_ANS VARCHAR2(500) NULL,
	PR_DATE DATE NULL
);

-- 상품질문게시판
ALTER TABLE QNA
	ADD CONSTRAINT PK_QNA -- 상품질문게시판 기본키
	PRIMARY KEY (
	PR_QNA_NO -- 상품질문글번호
	);

-- 결제
CREATE TABLE PAY (
	ORD_NO NUMBER(10) NOT NULL,
	PAY_TCODE VARCHAR2(10) NOT NULL,
	PAY_PRICE NUMBER(8) NOT NULL,
	PAY_DATE DATE NOT NULL,
	MEM_MILE NUMBER(7) NULL,
	MEM_COUPON VARCHAR2(40) NULL
);

-- 결제
ALTER TABLE PAY
	ADD CONSTRAINT PK_PAY -- 결제 기본키
	PRIMARY KEY (
	ORD_NO -- 결제번호
	);

-- 보유쿠폰
CREATE TABLE HAVE_COUPON (
	COP_NO NUMBER(5) NOT NULL,
	COP_DATE DATE NOT NULL,
	MEM_ID VARCHAR2(10) NOT NULL,
	COUPON_NO NUMBER(5) NOT NULL
);

-- 보유쿠폰
ALTER TABLE HAVE_COUPON
	ADD CONSTRAINT PK_HAVE_COUPON -- 보유쿠폰 기본키
	PRIMARY KEY (
	COP_NO -- 보유쿠폰번호
	);

-- 쿠폰
CREATE TABLE COUPONS (
	COUPON_NO NUMBER(5) NOT NULL,
	COUPON_NAME VARCHAR2(40) NOT NULL
);

-- 쿠폰
ALTER TABLE COUPONS
	ADD CONSTRAINT PK_COUPONS -- 쿠폰 기본키
	PRIMARY KEY (
	COUPON_NO -- 쿠폰번호
	);

-- 상품게시판
CREATE TABLE PROD_BOARD (
	PROD_NO NUMBER(10) NOT NULL,
	PROD_COLOR VARCHAR2(10) NOT NULL,
	PROD_NAME VARCHAR2(50) NOT NULL,
	PROD_DETAIL VARCHAR2(500) NOT NULL,
	PROD_COST NUMBER(7) NOT NULL,
	LPROD_NO VARCHAR2(10) NOT NULL,
	PROD_RANK NUMBER(3) NULL
);

-- 상품게시판
ALTER TABLE PROD_BOARD
	ADD CONSTRAINT PK_PROD_BOARD -- 상품게시판 기본키
	PRIMARY KEY (
	PROD_NO -- 상품번호
	);

-- 전체질문게시판
CREATE TABLE TOTAL_QNA (
	TO_QNA_NO NUMBER(5) NOT NULL,
	TO_QNA_TITLE VARCHAR2(50) NOT NULL,
	TO_QNA_CONTENT VARCHAR2(500) NOT NULL,
	TO_QNA_DATE DATE NOT NULL,
	MEM_ID VARCHAR2(10) NULL,
	TO_ANS VARCHAR2(500) NULL,
	TO_DATE DATE NULL
);

-- 전체질문게시판
ALTER TABLE TOTAL_QNA
	ADD CONSTRAINT PK_TOTAL_QNA -- 전체질문게시판 기본키
	PRIMARY KEY (
	TO_QNA_NO -- 전체질문글번호
	);

-- 사이즈별 상품
ALTER TABLE PROD_SIZE
	ADD CONSTRAINT FK_PROD_BOARD_TO_PROD_SIZE -- 상품게시판 -> 사이즈별 상품
	FOREIGN KEY (
	PROD_NO -- 상품번호
	)
	REFERENCES PROD_BOARD ( -- 상품게시판
	PROD_NO -- 상품번호
	);

-- 리뷰
ALTER TABLE REVIEW
	ADD CONSTRAINT FK_PROD_SIZE_TO_REVIEW -- 사이즈별 상품 -> 리뷰
	FOREIGN KEY (
	SPROD_NO -- 사이즈별 상품번호
	)
	REFERENCES PROD_SIZE ( -- 사이즈별 상품
	SPROD_NO -- 사이즈별 상품번호
	);

-- 리뷰
ALTER TABLE REVIEW
	ADD CONSTRAINT FK_MEMBER_TO_REVIEW -- 회원 -> 리뷰
	FOREIGN KEY (
	MEM_ID -- 회원아이디
	)
	REFERENCES MEMBER ( -- 회원
	MEM_ID -- 회원아이디
	);

-- 주문
ALTER TABLE ORDERS
	ADD CONSTRAINT FK_MEMBER_TO_ORDERS -- 회원 -> 주문
	FOREIGN KEY (
	MEM_ID -- 회원아이디
	)
	REFERENCES MEMBER ( -- 회원
	MEM_ID -- 회원아이디
	);

-- 환불
ALTER TABLE REFUND
	ADD CONSTRAINT FK_PAY_TO_REFUND -- 결제 -> 환불
	FOREIGN KEY (
	ORD_NO -- 환불번호
	)
	REFERENCES PAY ( -- 결제
	ORD_NO -- 결제번호
	);

-- 주문상세
ALTER TABLE DEORDER
	ADD CONSTRAINT FK_ORDERS_TO_DEORDER -- 주문 -> 주문상세
	FOREIGN KEY (
	ORD_NO -- 주문번호
	)
	REFERENCES ORDERS ( -- 주문
	ORD_NO -- 주문번호
	);

-- 주문상세
ALTER TABLE DEORDER
	ADD CONSTRAINT FK_PROD_SIZE_TO_DEORDER -- 사이즈별 상품 -> 주문상세
	FOREIGN KEY (
	SPROD_NO -- 사이즈별 상품번호
	)
	REFERENCES PROD_SIZE ( -- 사이즈별 상품
	SPROD_NO -- 사이즈별 상품번호
	);

-- 공지사항
ALTER TABLE NOTICE
	ADD CONSTRAINT FK_ADMIN_TO_NOTICE -- 관리자 -> 공지사항
	FOREIGN KEY (
	ADM_ID -- 관리자아이디
	)
	REFERENCES ADMIN ( -- 관리자
	ADM_ID -- 관리자아이디
	);

-- 상품질문게시판
ALTER TABLE QNA
	ADD CONSTRAINT FK_MEMBER_TO_QNA -- 회원 -> 상품질문게시판
	FOREIGN KEY (
	MEM_ID -- 회원아이디
	)
	REFERENCES MEMBER ( -- 회원
	MEM_ID -- 회원아이디
	);

-- 상품질문게시판
ALTER TABLE QNA
	ADD CONSTRAINT FK_PROD_SIZE_TO_QNA -- 사이즈별 상품 -> 상품질문게시판
	FOREIGN KEY (
	SPROD_NO -- 사이즈별 상품번호
	)
	REFERENCES PROD_SIZE ( -- 사이즈별 상품
	SPROD_NO -- 사이즈별 상품번호
	);

-- 결제
ALTER TABLE PAY
	ADD CONSTRAINT FK_PAY_TYPE_TO_PAY -- 결제수단 -> 결제
	FOREIGN KEY (
	PAY_TCODE -- 결제수단코드
	)
	REFERENCES PAY_TYPE ( -- 결제수단
	PAY_TCODE -- 결제수단코드
	);

-- 결제
ALTER TABLE PAY
	ADD CONSTRAINT FK_ORDERS_TO_PAY -- 주문 -> 결제
	FOREIGN KEY (
	ORD_NO -- 결제번호
	)
	REFERENCES ORDERS ( -- 주문
	ORD_NO -- 주문번호
	);

-- 보유쿠폰
ALTER TABLE HAVE_COUPON
	ADD CONSTRAINT FK_MEMBER_TO_HAVE_COUPON -- 회원 -> 보유쿠폰
	FOREIGN KEY (
	MEM_ID -- 회원아이디
	)
	REFERENCES MEMBER ( -- 회원
	MEM_ID -- 회원아이디
	);

-- 보유쿠폰
ALTER TABLE HAVE_COUPON
	ADD CONSTRAINT FK_COUPONS_TO_HAVE_COUPON -- 쿠폰 -> 보유쿠폰
	FOREIGN KEY (
	COUPON_NO -- 쿠폰번호
	)
	REFERENCES COUPONS ( -- 쿠폰
	COUPON_NO -- 쿠폰번호
	);

-- 상품게시판
ALTER TABLE PROD_BOARD
	ADD CONSTRAINT FK_LPROD_TO_PROD_BOARD -- 상품분류 -> 상품게시판
	FOREIGN KEY (
	LPROD_NO -- 상품분류코드
	)
	REFERENCES LPROD ( -- 상품분류
	LPROD_NO -- 상품분류코드
	);

-- 전체질문게시판
ALTER TABLE TOTAL_QNA
	ADD CONSTRAINT FK_MEMBER_TO_TOTAL_QNA -- 회원 -> 전체질문게시판
	FOREIGN KEY (
	MEM_ID -- 회원아이디
	)
	REFERENCES MEMBER ( -- 회원
	MEM_ID -- 회원아이디
	);