--상의
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000001, 'WHITE', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'S');
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000002, 'WHITE', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'M');
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000003, 'WHITE', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'L');
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000004, 'WHITE', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'XL');
 

 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000005, 'BLACK', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'S');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000006, 'BLACK', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'M');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000007, 'BLACK', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'L');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000008, 'BLACK', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'XL');
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000009, 'GRAY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'S');    
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000010, 'GRAY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'M');    
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000011, 'GRAY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'L');   
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000012, 'GRAY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'XL');    
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000013, 'NAVY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'S');     
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000014, 'NAVY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'M');     
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000015, 'NAVY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'L');     
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000016, 'NAVY', '지프 하프넥 엠로고 맨투맨', '산맥 일러스트로 포인트를 준 하프넥 맨투맨 티셔츠', 69000, 'B0001', 'XL');     
 
 
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000017, 'NAVY', '예스아이씨 아치 로고 후드티', '가운데에 빨간색 로고가 있는 후드티', 84000, 'B0001', 'S');    
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000018, 'NAVY', '예스아이씨 아치 로고 후드티', '가운데에 빨간색 로고가 있는 후드티', 84000, 'B0001', 'M');    
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000019, 'NAVY', '예스아이씨 아치 로고 후드티', '가운데에 빨간색 로고가 있는 후드티', 84000, 'B0001', 'L');    
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000020, 'NAVY', '예스아이씨 아치 로고 후드티', '가운데에 빨간색 로고가 있는 후드티', 84000, 'B0001', 'XL');    
  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000021, 'NAVY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'S');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000022, 'NAVY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'M'); 
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000023, 'NAVY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'L'); 
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000024, 'NAVY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'XL'); 
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000025, 'GREEN', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'S');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000026, 'GREEN', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'M');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000027, 'GREEN', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'L');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000028, 'GREEN', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'XL');  
 
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000029, 'GRAY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'S');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000030, 'GRAY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'M');    
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000031, 'GRAY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'L');    
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000032, 'GRAY', '커버낫 럭비 맨투맨', '럭비 티셔츠를 커버낫만의 스타일로 해석하여 디자인한 럭비 맨투맨', 79000, 'B0001', 'XL');   
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000033, 'WHITE', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'S'); 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000034, 'WHITE', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'M');   
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000035, 'WHITE', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'L');   
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000036, 'WHITE', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'XL');   
  
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000037, 'BLACK', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'S');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000038, 'BLACK', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'M');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000039, 'BLACK', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'L');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000040, 'BLACK', '와릿이즌 서핑엔젤 반팔 티셔츠', '바나나가 서핑보드를 타는 그림이 그려진 반팔 티셔츠', 39000, 'B0001', 'XL');
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000041, 'WHITE', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'S');
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000042, 'WHITE', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'M');
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000043, 'WHITE', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'L');
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000044, 'WHITE', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'XL');
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000045, 'BLACK', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'S');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000046, 'BLACK', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'M');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000047, 'BLACK', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'L');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000048, 'BLACK', '지오다노 레이어드 반팔 티셔츠', '여유 있는 기장감으로 다양한 상의 안에 레이어드 할 수 있는 티셔츠', 19800, 'B0001', 'XL');
 
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000049, 'GRAY', '페플 오리지널무지 기모 후드티', '두툼한 두께감의 기모 원단에 오랜 세탁에도 축률이 적은 보온성이 뛰어난 제품', 32500, 'B0001', 'S'); 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000050, 'GRAY', '페플 오리지널무지 기모 후드티', '두툼한 두께감의 기모 원단에 오랜 세탁에도 축률이 적은 보온성이 뛰어난 제품', 32500, 'B0001', 'M'); 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000051, 'GRAY', '페플 오리지널무지 기모 후드티', '두툼한 두께감의 기모 원단에 오랜 세탁에도 축률이 적은 보온성이 뛰어난 제품', 32500, 'B0001', 'L'); 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000052, 'GRAY', '페플 오리지널무지 기모 후드티', '두툼한 두께감의 기모 원단에 오랜 세탁에도 축률이 적은 보온성이 뛰어난 제품', 32500, 'B0001', 'XL');
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000053, 'RED', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'S');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000054, 'RED', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'M');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000055, 'RED', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'L');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000056, 'RED', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'XL');
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000057, 'GREEN', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'S'); 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000058, 'GREEN', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'M');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000059, 'GREEN', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'L');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000060, 'GREEN', '챔피온 파워블랜드 무지 맨투맨', '왼쪽 소매에 C로고 패치 포인트가 있는 무지 맨투맨', 69000, 'B0001', 'XL');   
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000061, 'PURPLE', '에프씨엠엠 클럽 에센셜 맨투맨', '왼쪽에 작은 로고가 있는 기모 맨투맨', 30000, 'B0001', 'S');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000062, 'PURPLE', '에프씨엠엠 클럽 에센셜 맨투맨', '왼쪽에 작은 로고가 있는 기모 맨투맨', 30000, 'B0001', 'M');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000063, 'PURPLE', '에프씨엠엠 클럽 에센셜 맨투맨', '왼쪽에 작은 로고가 있는 기모 맨투맨', 30000, 'B0001', 'L');
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000064, 'PURPLE', '에프씨엠엠 클럽 에센셜 맨투맨', '왼쪽에 작은 로고가 있는 기모 맨투맨', 30000, 'B0001', 'XL');
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000065, 'GRAY', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'S');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000066, 'GRAY', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'M');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000067, 'GRAY', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'L');  
  INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000068, 'GRAY', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'XL');  
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000069, 'BEIGE', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'S');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000070, 'BEIGE', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'M');      
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000071, 'BEIGE', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'L');      
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000072, 'BEIGE', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'XL');     
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000073, 'BROWN', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'S');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000074, 'BROWN', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'M');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000075, 'BROWN', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'L');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000076, 'BROWN', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'XL'); 
 
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000077, 'KHAKI', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'S');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000078, 'KHAKI', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'M');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000079, 'KHAKI', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'L');  
 INSERT INTO PROD_BOARD(PROD_NO, PROD_COLOR, PROD_NAME, PROD_DETAIL, PROD_COST, LPROD_NO, PROD_SIZE)
 VALUES(2000000080, 'KHAKI', '예일 투톤 아치 후드티', '가운데에 로고가 그려진 오버핏 후드티', 79000, 'B0001', 'XL'); 

INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000081, 'BURGUNDY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','S');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000082, 'BURGUNDY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','M');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000083, 'BURGUNDY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','L');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000084, 'BURGUNDY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','XL');  
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000085, 'IVORY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','S');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000086, 'IVORY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','M');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000087, 'IVORY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','L');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000088, 'IVORY', '리 빅 트위치 루즈핏 후드티', '트위치 로고가 빅 사이즈로 그려져 있으며 자연스러운 루즈핏의 후드티', 79000, 'B0001','XL');   

INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000089, 'OLIVE', '티떠블유엔 슬레이크 후드티', '아치형태의 자수와 트윌 조직감의 원단 아플리케가 특징인 후드티', 38900, 'B0001','S');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000090, 'OLIVE', '티떠블유엔 슬레이크 후드티', '아치형태의 자수와 트윌 조직감의 원단 아플리케가 특징인 후드티', 38900, 'B0001','M');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000091, 'OLIVE', '티떠블유엔 슬레이크 후드티', '아치형태의 자수와 트윌 조직감의 원단 아플리케가 특징인 후드티', 38900, 'B0001','L');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000092, 'OLIVE', '티떠블유엔 슬레이크 후드티', '아치형태의 자수와 트윌 조직감의 원단 아플리케가 특징인 후드티', 38900, 'B0001','XL');  
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000093, 'MINT', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','S');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000094, 'MINT', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','M');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000095, 'MINT', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','L');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000096, 'MINT', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','XL');  
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000097, 'CHARCOAL', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','S'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000098, 'CHARCOAL', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','M');
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000099, 'CHARCOAL', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','L');
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000100, 'CHARCOAL', '엠엠엘지 1987엠엠엘지 후드티', '원단이 소프트하고 얇은 두께의 기모감으로 보온력이 좋은 후드티', 79000, 'B0001','XL');
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000101, 'PINK', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','S');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000102, 'PINK', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','M');    
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000103, 'PINK', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','L');    
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000104, 'PINK', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','XL');    
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000105, 'YELLOW', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','S');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000106, 'YELLOW', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','M'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000107, 'YELLOW', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','L'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000108, 'YELLOW', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','XL'); 
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000109, 'PURPLE', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','S');         
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000110, 'PURPLE', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','M');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000111, 'PURPLE', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','L');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000112, 'PURPLE', '그루브라임 로케이션 반팔 티셔츠', '부드러운 터치감의 원단에 내구성과 신축성이 좋은 반팔티', 58000, 'B0001','XL');  
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000113, 'ORANGE', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','S');   
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000114, 'ORANGE', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','M'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000115, 'ORANGE', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','L'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000116, 'ORANGE', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','XL'); 
 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000117, 'BURGUNDY', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','S');  
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000118, 'BURGUNDY', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','M'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000119, 'BURGUNDY', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','L'); 
INSERT INTO PROD_BOARD(PROD_NO,PROD_COLOR,PROD_NAME,PROD_DETAIL,PROD_COST,LPROD_NO,PROD_SIZE)
 VALUES(2000000120, 'BURGUNDY', '디스이즈네버댓 티 로고 반팔 티셔츠', '가운데와 뒤에 작은 로고가 그려져 있는 반팔티', 39000, 'B0001','XL'); 