INSERT INTO PAY_TYPE(PAY_TCODE,PAY_TNAME) VALUES('A001', '무통장입금');
INSERT INTO PAY_TYPE(PAY_TCODE,PAY_TNAME) VALUES('B001', '카드');

INSERT INTO ADMIN VALUES('system', 'java', 123456789, '국민');

INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40001, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40002, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40003, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40004, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40005, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40006, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40007, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40008, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40009, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40010, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40011, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40012, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40013, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40014, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40015, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40016, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40017, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40018, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40019, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40020, 'MEMBER COUPON');
--BRONZE
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10001,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10002,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10003,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10004,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10005,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10006,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10007,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10008,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10009,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10010,'BRONZE COUPON');

INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10011,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10012,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10013,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10014,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10015,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10016,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10017,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10018,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10019,'BRONZE COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(10020,'BRONZE COUPON');

--SILVER
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20001,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20002,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20003,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20004,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20005,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20006,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20007,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20008,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20009,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20010,'SILVER COUPON');

INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20011,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20012,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20013,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20014,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20015,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20016,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20017,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20018,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20019,'SILVER COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(20020,'SILVER COUPON');

--GOLD 
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30001,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30002,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30003,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30004,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30005,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30006,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30007,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30008,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30009,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30010,'GOLD COUPON');

INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30011,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30012,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30013,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30014,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30015,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30016,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30017,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30018,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30019,'GOLD COUPON');
INSERT INTO COUPONS(COUPON_NO,COUPON_NAME) VALUES(30020,'GOLD COUPON');
COMMIT;