INSERT INTO MEMBER(MEM_ID, MEM_NAME, MEM_PASS, MEM_ADDR, MEM_BIR, MEM_RANK, MEM_MILE, MEM_BANK, MEM_ACC)
VALUES('abc123', 'È«±æµ¿', 'java', '´ëÀü ¼­±¸ µÐ»êµ¿', '1998/08/11', 'MEMBER', 1000, '±¹¹Î', 123456789);

INSERT INTO HAVE_COUPON(COP_NO, COP_DATE, MEM_ID, COUPON_NO)
VALUES(,SYSDATE, 'abc123', 

INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40001, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40002, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40003, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40004, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40005, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40006, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40007, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40008, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40009, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40010, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40011, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40012, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40013, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40014, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40015, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40016, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40017, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40018, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40019, 'MEMBER COUPON');
INSERT INTO COUPONS(COUPON_NO, COUPON_NAME)
VALUES(40020, 'MEMBER COUPON');

INSERT INTO HAVE_COUPON(COP_NO, COP_DATE, MEM_ID, COUPON_NO)
VALUES(90001, SYSDATE, 'abc123', 40001);

SELECT A.COUPON_NO,
       A.MEM_ID,
       B.COUPON_NAME
  FROM HAVE_COUPON A, COUPONS B      
 WHERE A.COUPON_NO = B.COUPON_NO
   AND A.MEM_ID = 'abc123';
   
INSERT INTO ORDERS(ORD_NO, MEM_ID, ORD_PRICE, ORD_DATE)
VALUES (550001, 'abc123', 79000, SYSDATE);
 
INSERT INTO DEORDER(ORD_NO, SPROD_NO, DEORDER_QTY)
VALUES (550001, 100001, 1);
    
SELECT B.ORD_NO,
       A.PROD_NAME,
       A.PROD_COLOR,
       A.PROD_COST,
       B.MEM_ID,
       A.PROD_NO,
       C.SPROD_NO,
       C.SPROD_SIZE,
       D.DEORDER_QTY,
       B.ORD_DATE
  FROM PROD_BOARD A, ORDERS B, PROD_SIZE C, DEORDER D
 WHERE A.PROD_NO = B.PROD_NO
   AND C.SPROD_NO = D.SPROD_NO
   AND B.MEM_ID = 'abc123'
 ORDER BY 1;
 
 SELECT B.ORD_NO,
        A.PROD_NAME,
			 A.PROD_COLOR,
                  A.PROD_COST,
			   B.MEM_ID,
			     A.PROD_NO,
			     C.SPROD_NO,
			    C.SPROD_SIZE,
			      D.DEORDER_QTY,
			      B.ORD_DATE
		 FROM PROD_BOARD A, ORDERS B, PROD_SIZE C, DEORDER D
			 WHERE A.PROD_NO = B.PROD_NO
		  AND C.SPROD_NO = D.SPROD_NO
			     AND B.MEM_ID = 'abc123'
			   ORDER BY B.ORD_NO



